= Conclusion

And that's the end of this short guide.
That said, for a short guide, we’ve still covered quite a bit.
Here’s a quick recap of what we covered.
We learned:

* Some essential Docker terminology
* How to install Docker
* How to build a local development environment using _Docker Compose_
* The essentials of how to debug that environment when things go wrong
* How to run tests in a Docker Compose environment from the host machine
* How to containerise an application and push it to a Docker registry
* How to build a deployment configuration using Docker Swarm
* How to deploy it to a non-development environment using _Docker Stack_

Sure, there have been quite a number of steps requiring, perhaps, too many different Docker commands—_my pet peeve with Docker_, but, we're done!

I've taken some shortcuts to keep the guide as concise as possible.
What’s more, there are so many things that I've not covered, including:

* How to create a more sophisticated image
* How to create a more sophisticated deployment configuration
* The security implications of the container we've created and deployed
* How to roll back, update, and destroy a deployment

However, for a short guide what we’ve covered is more than enough; wouldn’t you agree?
I hope that you've been able to follow the guide successfully and in the process learned a lot.
If you've had any problems, want to know more, or want to suggest other ways to do it, mailto:matthew@matthewsetter.com[please email me your feedback].
I’m keen to ensure that there are no bugs in this guide and that it stays up to date.
