= Conclusion

And that's the end of the guide.
We've covered how to containerise an application, how to build a deployment configuration using Docker Swarm, and deploy it to a non-development environment using Docker Stack.
Yes, there have been quite a number of steps, and perhaps too many Docker commands—_my pet peeve with Docker_.

*But, we're there!*

I've taken some shortcuts to keep the post as short as possible.
And there are so many things that I've not covered, such as:

* Creating a more sophisticated image or deployment configuration
* Considered the security implications of the container we've deployed
* Considered such requirements such as how to roll back a release
* Seen how to update an existing release
* Seen how to destroy an existing swarm

However, for a simple example, it's sufficient.
Ideally, I'd like to expand on this post at some stage.
However, I didn't want to overwhelm you today.

I hope that you've been able to follow the instructions here successfully, and in the process learned a lot.
If you've had any problems, want to know more, or want to suggest other ways to do it, add your feedback in the comments.

