= So How Do I Debug a Docker Configuration?

Now that you’ve learned how to create a basic setup with Docker Compose, it’s important to learn how to do basic debugging.
That way, if and when things go wrong you know how to figure out what’s going wrong and why. 
That way you can either fix it or ask someone else for help, if you can’t fix it on your own. 
So here's a basic process you can follow to find out what happened, and get your containers up and running properly.

To put this into greater context, when I was first getting stated with Docker, I was trying to create a Docker development environment for building a new Mezzio application.
I'd created a basic container configuration, very similar to the one in this short guide, using the `php:7-apache` and MariaDB containers and thought that everything should work.

However when I attempted to run the installer, the database’s hostname wasn't able to be resolved, so the install failed.
This seemed rather strange. 
I didn't see anything strange in the console output (or so I thought) after I started the containers.

The first thing I thought to do was to access bash in the webserver container to try and ping the database to see if it could be accessed.
Sure enough, I wasn't able to.

I thought that I must have misconfigured something.
But on reviewing the configuration with a known working setup, nothing seemed out of the ordinary.

== Step 1. Check the Container’s State

So I decided to have a quick look at the container’s state, by running `docker-compose ps`.
On doing so I saw the following output; note the state of the database container (`Exit 1`).

[source,console,linenums,highlight=1..1]
----
        Name                      Command               State          Ports
-----------------------------------------------------------------------------------
core1000_database_1    docker-entrypoint.sh mysqld      Exit 1
core1000_webserver_1   docker-php-entrypoint apac ...   Up       0.0.0.0:80->80/tcp
----

While not _that_ clear or insightful, it means that the container wasn't able to start successfully, and had exited prematurely.
However as the webserver container’s state is set to `Up`, it is running properly.

NOTE: To get the status of an individual container, add its name to the end of the command.
For example: `docker-compose ps database`.

== Step 2. What Do the Logs Say?

Given that the database container had exited prematurely, it was time to get more detailed information about the problem that caused this to happen.
To do that, I needed to find out what the logs for the container contained.

This is not so different from any other form of debugging.
If you want to figure out what's going on, the best place to look are the logs.
They contain information such as ports already being in use, server misconfiguration, and so on.

To have a look at the logs for the database container, used https://docs.docker.com/compose/reference/logs/[the `logs` command].
Here’s an example of how to do so: 

[source,console]
----
docker-compose logs --follow database
----

TIP: You don't have to include the `--follow` flag.
I decided to as I wanted to reload the page a few times and see the output scroll by, instead of having to call the command repeatedly.
On doing that, here's what I saw:

[source,console]
----
database_1   | error: database is uninitialized and password option is not specified
database_1   | You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
----

== Step 3. Fix the Problem. Restart or Rebuild the Containers. Check Again

Turns out, I'd _almost_ configured the containers correctly. 
Unfortunately I’d forgotten to configure https://hub.docker.com/_/mariadb/[a mandatory setting] for the MariaDB container.
Given that, I:

* Added an environment value for `MYSQL_ROOT_PASSWORD` to docker-compose.yml
* Saved the file 
* Ran `docker-compose up -d --build database` to rebuild and restart the database container

As the container started, I payed closer attention to the console output. 
I didn’t see anything that indicated a problem or error.
But to be sure I ran `docker-compose ps` again, to ensure that the container was running properly.

Sure enough, everything was working as expected.
Given that, I now had a working installation ready to use.
**Achievement unlocked!**

[source,console]
----
        Name                      Command               State           Ports
--------------------------------------------------------------------------------------
core1000_database_1    docker-entrypoint.sh mysqld      Up      0.0.0.0:3306->3306/tcp
core1000_webserver_1   docker-php-entrypoint apac ...   Up      0.0.0.0:80->80/tcp
----

== Chapter Recap

While this hasn't been the most in-depth of guides on how to debug a Docker configuration, built with Docker Compose, it's covered the basics.
It's covered how to determine if a container isn't working and how to find out more detailed information in the logs, so that you can correct problems, or ask for help if you’re not able to do so on your own.

To summarise, follow these steps to debug a Docker Compose-based container configuration:

. Use `docker-compose ps` to see the state of all the containers
. Use `docker-compose logs --follow` to inspect the logs to find out what errors are occurring
. Fix the problem
. Restart the container with `docker-compose up -d --build`
. Lather, rinse, repeat

== Further Reading

If you need any further information, check out https://docs.docker.com/compose/reference/[the official Docker Compose documentation].
